/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    SHOPIFY_API_SECRET: {
      type: 'sst.sst.Secret';
      value: string;
    };
    TagVipsFunction: {
      name: string;
      type: 'sst.aws.Function';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
