name: Deploy to SST (Production)

on:
  push:
    branches:
      - main
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Initialize SST
        run: npx sst install

      - name: Run ESLint
        run: pnpm lint

      - name: Check Prettier formatting
        run: pnpm format:check

      - name: TypeScript type check
        run: pnpm typecheck

      - name: Run unit tests
        run: pnpm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npx sst deploy --stage production --verbose

      - name: Verify deployment
        run: |
          echo "✅ Deployment completed successfully"
          echo "🚀 Service is now live in production"

      - name: Check deployment logs on failure
        if: ${{ failure() }}
        run: |
          echo "❌ Deployment failed. Checking logs..."
          if [ -f .sst/log/sst.log ]; then
            echo "SST Logs:"
            cat .sst/log/sst.log
          else
            echo "No SST log file found"
          fi
